# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRicercaNLP():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ricercaNLP(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1333, 1040)
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > svg").click()
    self.driver.find_element(By.ID, "user-input").click()
    self.driver.find_element(By.ID, "user-input").send_keys("voglio una maglia")
    self.driver.find_element(By.CSS_SELECTOR, ".ml-2").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".h-48")
    assert len(elements) > 0
  
