# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchProduct():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchProduct(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1525, 1040)
    self.driver.find_element(By.NAME, "product_name").click()
    self.driver.find_element(By.NAME, "product_name").send_keys("ngewjgelkwtjeklwt")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-black").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".grid > h1")
    assert len(elements) > 0
  
