# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegistrazione():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registrazione(self):
    self.driver.get("http://127.0.0.1:5000/registrati")
    self.driver.set_window_size(1525, 1040)
    self.driver.find_element(By.ID, "firstName").send_keys("Mario")
    self.driver.find_element(By.ID, "lastName").send_keys("Rossi")
    self.driver.find_element(By.ID, "date").send_keys("0002-05-15")
    self.driver.find_element(By.ID, "date").send_keys("0020-05-15")
    self.driver.find_element(By.ID, "date").send_keys("0200-05-15")
    self.driver.find_element(By.ID, "date").send_keys("2002-05-15")
    self.driver.find_element(By.ID, "numTel").send_keys("3987645129")
    self.driver.find_element(By.ID, "Maschio").click()
    self.driver.find_element(By.ID, "email").send_keys("wwrwrw@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Password1234!")
    self.driver.find_element(By.ID, "confirmPassword").send_keys("Password1234!")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-green-500").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "p:nth-child(3)")
    assert len(elements) > 0
  
