# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAggiuntadatispedizione():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_aggiuntadatispedizione(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(976, 1040)
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(3) path:nth-child(2)").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("alrossi@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Password1234!")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-green-500").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(3) path:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#addresses path:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#aggiungiIndirizzo > svg").click()
    self.driver.find_element(By.ID, "citta").click()
    self.driver.find_element(By.ID, "citta").send_keys("Battipaglia")
    self.driver.find_element(By.ID, "provincia").click()
    self.driver.find_element(By.ID, "provincia").send_keys("Salerno")
    self.driver.find_element(By.ID, "via").click()
    self.driver.find_element(By.ID, "via").send_keys("Sassari, 123")
    self.driver.find_element(By.ID, "cap").click()
    self.driver.find_element(By.ID, "cap").send_keys("84091")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-500").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#profile > svg")
    assert len(elements) > 0
  
