# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEliminaaccount():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_eliminaaccount(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1525, 1040)
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(3) > svg").click()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("54email@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Password1234!")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-green-500").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(3) > svg").click()
    self.driver.find_element(By.CSS_SELECTOR, "#settings > svg").click()
    self.driver.find_element(By.CSS_SELECTOR, "form > button").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "p:nth-child(3)")
    assert len(elements) > 0
  
