# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestModificapersonale():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_modificapersonale(self):
    self.driver.get("http://127.0.0.1:5000/direttore/login")
    self.driver.set_window_size(1649, 1040)
    self.driver.find_element(By.ID, "email").send_keys("alrossi3@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Password1234!")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-green-500").click()
    self.driver.find_element(By.CSS_SELECTOR, ".even:nth-child(4) .bg-blue-500").click()
    self.driver.find_element(By.ID, "tipo_personale").click()
    dropdown = self.driver.find_element(By.ID, "tipo_personale")
    dropdown.find_element(By.XPATH, "//option[. = 'Gestore Ordine']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-500").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".text-green-500")
    assert len(elements) > 0
  
